[project]
name = "okte-home-assistant"
version = "0.0.0"  # HA uses manifest.json for versioning
requires-python = ">=3.13"

[project.optional-dependencies]
dev = [
    "homeassistant",
    "ruff",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
